### PR TITLE
Updates

### PR DESCRIPTION
**Pull request by putianyi889**
- #218 
- #219 
- #229 
- Merge and generalise some other codes. 
- #212

### CODE REVIEW

**Comment by jishnub** [comment]
There seem to be quite a few somewhat unrelated changes in this PR. Could you split this into multiple PRs, so that it'll be easy to keep track of them?

**Comment by dlfivefifty** [comment]
Is this needed anymore?

**Comment by putianyi889** [comment]
Yes. There is still an unfiled change.

**Comment by putianyi889** [comment]
There is no feature change though, I think. Most are reorganising codes

**Pull request closed without merging**
