### PR TITLE
Add some specializations

### PR DESCRIPTION
**Pull request by kshyatt**
I got a migraine and didn't feel up to figuring out the broadcast semantics for the matrix versions, sorry :/. If anyone wants to edit this pr, go ahead. Should hopefully address https://github.com/FluxML/Zygote.jl/issues/261 .

### CODE REVIEW

**Comment by willtebbutt** [comment]
@kshyatt happy to help out with the `Matrix * Matrix` versions.

Before that though, I notice the current implementation goes with `StridedMatrix` etc rather than `AbstractMatrix`, which I would have thought will still leave us with GPU-related issues. Might it be better to go with `AbstractMatrix` etc instead, or am I missing something?

**Comment by kshyatt** [comment]
If you go with Abstract you get method ambiguity errors. I tried these on gpu and they seemed to work with scalar indexing off. CuArrays are subtypes of StridedArrays.

**Comment by willtebbutt** [comment]
> CuArrays are subtypes of StridedArrays.

This doesn't seem to hold on Julia 1.3.0-rc3 and CuArrays v1.2.1. Am I missing something?

> If you go with Abstract you get method ambiguity errors

Good point -- Abstract probably isn't ideal then.

**Comment by dlfivefifty** [comment]
We could overload both ` StridedMatrix ` and ` AbstractMatrix `

**Comment by kshyatt** [comment]
@willtebbutt i'll check what versions of CuArrays and Julia I used, might have just been a mistake on my part :)

The method ambiguity comes because there are already specializations for `(A::AbstractFill{<:Any, 2}, Z::Zeros{<:Any, 1}` iiirc (quoting from memory here sorry if the signature is wrong).

**Comment by kshyatt** [comment]
@willtebbutt I'm on the same Julia version and `CuArrays#master`, and I get:

```
julia> CuMatrix <: StridedArray
true

julia> a = cu(rand(10, 10));

julia> a isa CuMatrix
true

julia> a isa StridedArray
true

julia> a isa StridedMatrix
true
```

**Pull request merged**
