### PR TITLE
Import deps transitively in SparseArrays extension

### PR DESCRIPTION
**Pull request by jishnub**
Following the suggestion in https://github.com/JuliaArrays/FillArrays.jl/pull/303#discussion_r1377218507 and following https://github.com/JuliaStats/LogExpFunctions.jl/pull/63

### CODE REVIEW

**Comment by jishnub** [comment]
Good to be merged? This may be necessary, going by the comments linked above.

**Comment by jishnub** [comment]
Gentle bump

**Comment by dlfivefifty** [comment]
I'm going to be very slow for code review / merging over the next couple months so I suggest others take the lead

**Comment by jishnub** [comment]
Gentle bump

**Pull request merged**
