### PR TITLE
zero for OneElement

### PR DESCRIPTION
**Pull request by jishnub**
With this,
```julia
julia> v = OneElement(10, 3, 4)
4-element OneElement{Int64, 1, Tuple{Int64}, Tuple{Base.OneTo{Int64}}}:
  ⋅
  ⋅
 10
  ⋅

julia> zero(v)
4-element Zeros{Int64}

julia> v + zero(v) isa typeof(v)
true
```

### CODE REVIEW

**Comment by longemen3000** [comment]
Seems good to add. But before adding, what is the contract for `zero` when using with `AbstractArray`?. before merging, is there any advantage on returning `Zeros{T}`/`Ones{T}` instead of `OneElement{T}` ?

**Comment by jishnub** [comment]
The main advantage is that `typeof(x + zero(x))` will be the same as `typeof(x)`, in this case a `OneElement`. The sum of two `OneElement`s isn't a `OneElement`.

**Comment by jishnub** [comment]
I've updated this to return a zero based on the value and not the type. `zero(v::OneElement)` now tries to preserve the type of the array, which is often assumed elsewhere.
```julia
julia> using FillArrays

julia> v = OneElement(10, 3, 4)
4-element OneElement{Int64, 1, Tuple{Int64}, Tuple{Base.OneTo{Int64}}}:
  ⋅
  ⋅
 10
  ⋅

julia> zero(v)
4-element OneElement{Int64, 1, Tuple{Int64}, Tuple{Base.OneTo{Int64}}}:
 ⋅
 ⋅
 0
 ⋅
```

**Comment by jishnub** [comment]
Gentle bump

**Pull request merged**
