### PR TITLE
`Eigen` for `AbstractFill` and `eigvals` for `Tridiagonal{<:Number,<:AbstractFillVector}`

### PR DESCRIPTION
**Pull request by jishnub**
The various tridiagonal matrices that wrap `AbstractFillVector`s are Toeplitz matrices, and their eigenvalues may be computed analytically in `O(n)` time, and eigenvectors in `O(n^2)`. Aside from this, since a square `AbstractFillMatrix` is of rank-1, it has only one non-zero eigenvalue that may be computed trivially in `O(1)` time, and the eigenvectors may also be evaluated in `O(n^2)`.

```julia
julia> T = Tridiagonal(Fill(2,400), Fill(5,401), Fill(2,400));

julia> @btime eigvals($T);
  12.503 μs (1 allocation: 3.31 KiB)  # This PR
  8.211 ms (11 allocations: 1.37 MiB) # master

julia> @btime eigen($T);
  875.773 μs (4 allocations: 2.46 MiB) # This PR
  26.678 ms (16 allocations: 3.83 MiB) # master

julia> F = Fill(2, 40, 40);

julia> @btime eigvals($F); # This PR
  4.211 ns (0 allocations: 0 bytes)

julia> @btime eigen($F);
  1.444 μs (1 allocation: 12.62 KiB)

julia> @btime eigvals($(Matrix(F))); # as on aster
  106.181 μs (10 allocations: 27.94 KiB)
```

### CODE REVIEW

**Comment by jishnub** [comment]
I'm not fully sure about https://github.com/JuliaArrays/FillArrays.jl/pull/256/commits/d5ff1e4ac80c935b80a80683edd893de02f6c939, where I evaluate `sin(pi*q*j/(n+1))` iteratively. This is faster than calling `sinpi` on each iteration, but this might reduce the accuracy for large matrices as floating-point errors pile up. Should we revert this, and go back to calling `sinpi` in each iteration?

**Comment by dlfivefifty** [comment]
I don't really think this PR belongs here, it's too complicated for this package.... ToeplitzMatrices.jl would be a better home even if it means type-piracy...

**Comment by jishnub** [comment]
Perhaps this can be simplified somewhat by removing the eigenvalue sorting. The Toeplitz component may be moved to `ToeplitzMatrices`, but the eigen for `FillArrays` may remain here?

**Comment by dlfivefifty** [comment]
Yes I'm happy for the eigen for `Fill` to be here... just Toeplitz matrices becomes a bit too algorithmic and then its harder to maintain...

**Comment by jishnub** [comment]
I've moved the tridiagonal methods to ToeplitzMatrices.jl. I'm closing this for now, as eigen for Fill arrays is perhaps not a very useful operation (and it's trivial in any case)

**Pull request closed without merging**
