### PR TITLE
Fix conversion from Zeros to SparseMatrixCSC

### LINKED ISSUE #31: Fix sparse(::Zeros)
```julia
julia> sparse(Zeros(5,5))
ERROR: MethodError: convert(::Type{SparseMatrixCSC{Float64,Int64}}, ::Zeros{Float64,2,Tuple{Int64,Int64}}) is ambiguous. Candidates:
  convert(::Type{SparseMatrixCSC{Tv,Ti}}, Z::Zeros{T,2,SZ} where SZ) where {T, Tv, Ti} in FillArrays at /Users/sheehanolver/Projects/FillArrays.jl/src/FillArrays.jl:273
  convert(T::Type{#s549} where #s549<:SparseMatrixCSC, m::AbstractArray{T,2} where T) in SparseArrays at /Users/sheehanolver/Projects/julia/usr/share/julia/stdlib/v1.0/SparseArrays/src/sparsematrix.jl:419
Possible fix, define
  convert(::Type{SparseMatrixCSC{Tv,Ti<:Integer}}, ::Zeros{T,2,SZ} where SZ)
Stacktrace:
 [1] sparse(::Zeros{Float64,2,Tuple{Int64,Int64}}) at /Users/sheehanolver/Projects/julia/usr/share/julia/stdlib/v1.0/SparseArrays/src/sparsematrix.jl:444
 [2] top-level scope at none:0
```

### PR DESCRIPTION
**Pull request by ararslan**
Fixes #31.

### CODE REVIEW

**Comment by ararslan** [comment]
Thanks! Okay to tag a v0.4.0, @dlfivefifty?

**Comment by dlfivefifty** [comment]
If it’s not a rush we should wait to https://github.com/JuliaArrays/FillArrays.jl/pull/54 to be merged

**Comment by ararslan** [comment]
Sure, not a big deal

**Comment by dlfivefifty** [comment]
Tagged!

**Pull request merged**
