### PR TITLE
Multiply and divide `OneElement` by a number

### PR DESCRIPTION
**Pull request by jishnub**
After this,
```julia
julia> OneElement(2, 3, 4)/2
4-element OneElement{Float64, 1, Tuple{Int64}, Tuple{Base.OneTo{Int64}}}:
  ⋅ 
  ⋅ 
 1.0
  ⋅ 
```

### CODE REVIEW

**Comment by dlfivefifty** [comment]
Should broadcasting also be supported?

**Comment by jishnub** [comment]
Yes, ideally, but we need to look into whether defining a broadcast style might be the way to go

**Comment by jishnub** [comment]
Coverage seems broken here, but this should be ready

**Comment by jishnub** [comment]
Gentle bump

**Pull request merged**
